@startuml
[*] --> ACCEPT
[*] --> BORROW
ACCEPT -> BORROW
ACCEPT --> ACCEPT_OUT_TIME
BORROW -> ALREADY_RET
BORROW -> BORROW_OUT_TIME
BORROW_OUT_TIME --> ALREADY_RET
ALREADY_RET --> DELETE
ACCEPT_OUT_TIME --> DELETE
DELETE -->[*]
ACCEPT:预约（等待同意预约申请)
BORROW:借阅
ACCEPT_OUT_TIME:预约超时
ALREADY_RET:已归还
BORROW_OUT_TIME:借阅超时
DELETE:已删除
@enduml